const express = require('express');
const router = express.Router();
const expertsRouter = require("./experts.route");
const usersRouter = require("./users.route");
const specialtiesRouter = require("./specialties.route");
const subSpecialtiesRouter = require("./subspecialties.route");
const calendarRouter = require("./calendar.route");
const stripeRouter = require("./stripe.route");
const authRouter = require("./auth.route");
const jaasRouter = require("./jaas.route");
const rdvRouter = require("./rdv.route");
const dashboardRouter = require("./dashboard.route");
const reviewsRouter = require("./reviews.route");
const promoRouter = require("./promo.route");
const adminRouter = require("./admin.route");

router.use("/experts", expertsRouter);
router.use("/users", usersRouter);
router.use("/specialties", specialtiesRouter);
router.use("/subspecialties", subSpecialtiesRouter);
router.use("/calendar", calendarRouter);
router.use("/stripe", stripeRouter);
router.use("/auth", authRouter);
router.use("/jaas", jaasRouter);
router.use("/rdv", rdvRouter);
router.use("/dashboard", dashboardRouter);
router.use("/reviews", reviewsRouter);
router.use("/promo", promoRouter);
router.use("/admin", adminRouter);

module.exports = router;